title: "何小龙的博客"
author: "何小龙 Leon.He"
description: "经验积累，技术总结"
more: "阅读全文 »"
url: "https://hexiaolong2008.github.io/"
baseurl: "/blog"
paginate: 4
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/twitter/"
  - github: "https://github.com/hexiaolong2008/blog"
  - envelope: "mailto:343005384@qq.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
